shampinion = open("infos\шампньон.txt", "r", encoding="utf8").read()
lisichka = open("infos\лисичка обыкновенная.txt", "r", encoding="utf8").read()
opyata = open("infos\опята.txt", "r", encoding="utf8").read()
gruzd = open("infos\груздь.txt", "r", encoding="utf8").read()
borowik = open("infos\белый гриб (боровик).txt", "r", encoding="utf8").read()
podberez = open("infos\подберёзовик.txt", "r", encoding="utf8").read()
podocin = open("infos\подосиновик.txt", "r", encoding="utf8").read()
ruzhik = open("infos\рыжик.txt", "r", encoding="utf8").read()
suroezka = open("infos\сыроежка.txt", "r", encoding="utf8").read()
maslenok = open("infos\маслёнок.txt", "r", encoding="utf8").read()
muhomor = open("infos\мухомор.txt", "r", encoding="utf8").read()
poganka = open("infos\бледная поганка.txt", "r", encoding="utf8").read()
satana = open("infos\сатанинский гриб.txt", "r", encoding="utf8").read()
lepiota = open("infos\лепиота коричнево-красная.txt", "r", encoding="utf8").read()
galerina = open("infos\галерина окаймлённая.txt", "r", encoding="utf8").read()
pautinic = open("infos\паутинник красивейший.txt", "r", encoding="utf8").read()
zhelchi = open("infos\желчный гриб.txt", "r", encoding="utf8").read()
lozhlisichka = open("infos\ложная лисичка.txt", "r", encoding="utf8").read()
lozhopenek = open("infos\ложный опёнок.txt", "r", encoding="utf8").read()
mizena = open("infos\мицена.txt", "r", encoding="utf8").read()